<?php $tabId = $elementId . 'filesCollectionsContainers' ?>

<a href="#<?php echo $tabId; ?>" class="tracy-toggle tracy-collapsed">Files collections containers</a>

<table id="<?php echo $tabId ?>" style="width: 100%" class="tracy-collapsed">
	<thead>
		<tr>
			<td><strong>Name</strong></td>
			<td><strong>Css collections</strong></td>
			<td><strong>Js collections</strong></td>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($filesCollectionsContainers as $filesCollectionsContainersName => $filesCollectionsContainer) {; ?>
			<tr>
				<td><?php echo $filesCollectionsContainersName; ?></td>
				<td><?php dump($filesCollectionsContainer->getCssCollections()); ?></td>
				<td><?php dump($filesCollectionsContainer->getJsCollections()); ?></td>
			</tr>
		<?php };?>
	</tbody>
</table>
