<?php $tabId = $elementId . 'filesCollections' ?>

<a href="#<?php echo $tabId; ?>" class="tracy-toggle">Files collections</a>

<table id="<?php echo $tabId ?>" style="width: 100%">
	<thead>
		<tr>
			<td><strong>Name</strong></td>
			<td><strong>Files</strong></td>
			<td><strong>Filters</strong></td>
			<td><strong>Type</strong></td>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($filesCollectionsByType as $filesCollectionsType => $filesCollections) {; ?>
			<?php foreach ($filesCollections as $filesCollectionName => $filesCollection) {; ?>
				<tr>
					<td><?php echo $filesCollectionName; ?></td>
					<td><?php dump($filesCollection->getFiles()); ?></td>
					<td><?php dump($filesCollection->getFilters()); ?></td>
					<td><?php echo $filesCollectionsType; ?></td>
				</tr>
			<?php };?>
		<?php };?>
	</tbody>
</table>
