<?php $tabId = $elementId . 'paths-placeholders' ?>

<a href="#<?php echo $tabId; ?>" class="tracy-toggle tracy-collapsed">Paths placeholders</a>

<table id="<?php echo $tabId ?>" style="width: 100%" class="tracy-collapsed">
	<thead>
		<tr>
			<td><strong>Placeholder</strong></td>
			<td><strong>Path</strong></td>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($pathsPlaceholders as $placeholder => $path) {; ?>
			<tr>
				<td><?php echo $placeholder; ?></td>
				<td><?php echo $path; ?></td>
			</tr>
		<?php };?>
	</tbody>
</table>
