<?php $tabId = $elementId . 'setup' ?>

<a href="#<?php echo $tabId; ?>" class="tracy-toggle">Setup</a>

<table id="<?php echo $tabId ?>" style="width: 100%">
	<thead>
		<tr>
			<td><strong>Option</strong></td>
			<td><strong>Value</strong></td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>Document root</td>
			<td><?php echo $documentRoot; ?></td>
		</tr>
		<tr>
			<td>Output dir</td>
			<td><?php echo $outputDir; ?></td>
		</tr>
		<tr>
			<td>Base path</td>
			<td>
				<?php
					$basePath = $outputDir;

					if ($documentRoot) {
						$basePath = str_replace($documentRoot, '', $outputDir);
					}
					echo $basePath
				?>
			</td>
		</tr>
		<tr>
			<td>Cache</td>
			<td><?php echo $cacheEnabled ? 'Enabled' : 'Disabled' ?></td>
		</tr>
		<tr>
			<td>Version</td>
			<td><?php echo $version; ?></td>
		</tr>
	</tbody>
</table>
