name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Install packages
          run: composer install --no-interaction

        - name: CS Check
          run: composer cs:check

        - name: PHPstan check
          run: composer phpstan:check

        - name: Unit Tests
          run: composer tester:check

        # - name: Coveralls
        #  uses: coverallsapp/github-action@1.1.3
        #  with:
        #    github-token: ${{ secrets.COVERALLS_TOKEN }}
        #    path-to-lcov: 'lcov.info'
